#-------------------------------------------------------------------------------
# Workflow configuration
#-------------------------------------------------------------------------------

name: "Desktop CI builds"
on:
  push:
  pull_request:
  workflow_dispatch:

#-------------------------------------------------------------------------------
# Define application name & version
#-------------------------------------------------------------------------------

env:
  APP_NAME: "WatchFlower"
  APP_VERSION: "6.0"
  QT_VERSION: "6.10.3"

#-------------------------------------------------------------------------------
# Workflow jobs
#-------------------------------------------------------------------------------

jobs:
  ## GNU/Linux build ###########################################################
  build-linux:
    name: "Linux CI build"
    runs-on: ubuntu-22.04
    steps:
      # Checkout repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # Install dependencies (from package manager)
      - name: Install dependencies (from package manager)
        run: |
             sudo apt-get install libgl1-mesa-dev libxkbcommon-x11-dev libx11-xcb-dev libzstd-dev -y;
             sudo apt-get install cmake ninja-build pkgconf libtool -y;
             sudo apt-get install libfuse2 appstream -y;

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          modules: qtconnectivity qtcharts qtpositioning

      # Setup env
      - name: Setup env
        run: |
             echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV
             qmake --version
             cmake --version
             ninja --version

      # Build application
      - name: Build application
        run: |
             cmake -B build/ -DCMAKE_BUILD_TYPE=Release -G Ninja
             cmake --build build/ --config Release

      # Deploy application
      - name: Deploy application
        run: ./deploy_linux.sh -p

      # Upload application ZIP
      - name: Upload application ZIP
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-linux64.tar.gz
          path: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-linux64.tar.gz

      # Upload AppImage
      - name: Upload AppImage
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-linux64.AppImage
          path: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-linux64.AppImage

  ## macOS build ###############################################################
  build-mac:
    name: "macOS CI build"
    runs-on: macos-15
    steps:
      # Checkout repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # Install dependencies (from package manager)
      #- name: Install dependencies (from package manager)
      #  run: |
      #       brew install qt6 cmake ninja

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          modules: qtconnectivity qtcharts qtpositioning

      # Setup env
      - name: Setup env
        run: |
             echo "CMAKE_BUILD_PARALLEL_LEVEL=`sysctl -n hw.logicalcpu`" >> $GITHUB_ENV
             qmake --version
             cmake --version
             ninja --version

      # Setup certificate(s)
      - name: Setup certificate(s)
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
          MACOS_CI_KEYCHAIN_PASSWORD: ${{ secrets.MACOS_CI_KEYCHAIN_PASSWORD }}
        run: |
            # Turn our base64-encoded certificate(s) back to a regular file(s)
            echo "$MACOS_CERTIFICATE" | base64 --decode > certificate.p12
            # Create a temporary headless keychain, import certificate, ...
            security create-keychain -p "$MACOS_CI_KEYCHAIN_PASSWORD" build.keychain
            security set-keychain-settings -lut 21600 build.keychain
            security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PASSWORD" build.keychain
            security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PASSWORD" build.keychain
            security list-keychains -s build.keychain "$(security list-keychains | tr -d '\"')"
            security default-keychain -s build.keychain

      # Build application
      - name: Build application
        run: |
             cmake -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
             cmake --build build/ --config Release

      # Deploy application
      - name: Deploy application
        env:
          MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
        run: ./deploy_macos.sh -n

      # Codesign application bundle
      - name: Codesign application bundle
        run: |
          /usr/bin/codesign --deep --force --options runtime \
            --entitlements "assets/macos/${{ env.APP_NAME }}.entitlements" \
            --sign "${{ secrets.MACOS_CERTIFICATE_NAME }}" \
            bin/${{ env.APP_NAME }}.app

      # Notarize application bundle
      - name: Notarize application bundle
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          echo "Create keychain profile"
          xcrun notarytool store-credentials "notarytool-profile" --apple-id "$APPLE_ID" --team-id "$APPLE_TEAM_ID" --password "$APPLE_APP_SPECIFIC_PASSWORD"
          echo "Creating temp notarization archive"
          ditto -c -k --keepParent "bin/${{ env.APP_NAME }}.app" "bin/notarization.zip"
          echo "Notarize app"
          xcrun notarytool submit "bin/notarization.zip" --keychain-profile "notarytool-profile" --wait
          echo "Attach staple"
          xcrun stapler staple "bin/${{ env.APP_NAME }}.app"
          echo "Creating notarized archive"
          ditto -c -k --keepParent "bin/${{ env.APP_NAME }}.app" "${{ env.APP_NAME }}-${{ env.APP_VERSION }}-macOS.zip"

      # Upload application bundle
      - name: Upload application bundle
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-macOS.zip
          path: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-macOS.zip

  ## Windows build #############################################################
  build-windows:
    name: "Windows CI build"
    runs-on: windows-2022
    steps:
      # Checkout repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # Configure MSVC
      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_64

      # Install NSIS (already installed in 'windows-2022')
      #- name: Install NSIS
      #  run: |
      #       Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
      #       scoop bucket add extras
      #       scoop install nsis

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          modules: qtconnectivity qtcharts qtpositioning
          arch: 'win64_msvc2022_64'

      # Setup env
      - name: Setup env
        run: |
             qmake --version
             cmake --version

      # Build application
      - name: Build application
        run: |
             cmake -B build/ -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles"
             cd build/
             nmake

      # Deploy application
      - name: Deploy application
        run: sh deploy_windows.sh -p

      # Upload application ZIP
      - name: Upload application ZIP
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-win64.zip
          path: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-win64.zip

      # Upload NSIS installer
      - name: Upload NSIS installer
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-win64.exe
          path: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-win64.exe
